"""Message to Conversation

Revision ID: 0fec2908553a
Revises: 3061fe2138cd
Create Date: 2026-03-01 12:44:49.834872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fec2908553a'
down_revision: Union[str, Sequence[str], None] = '3061fe2138cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('conversation_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_column('messages', 'conversation_id')
    # ### end Alembic commands ###
